const uestcLocations = [
  "South Gate 1",
  "South Gate 2",
  "West Gate 1",
  "West Gate 2",
  "Hospital Gate",
  "Hospital Gate Parking",
  "Main Building Parking",
  "South Gate Parking",
  "Pinxue Building Parking",
  "West Gate Parking",
  "Dormitory Building No. 1",
  "Dormitory Building No. 2",
  "Dormitory Building No. 4",
  "Dormitory Building No. 32",
  "Pinxue Teaching Building A",
  "Pinxue Teaching Building B",
  "Pinxue Teaching Building C",
  "Liren Teaching Building A",
  "Liren Teaching Building B",
  "Main Building A1",
  "Main Building A2",
  "Main Building B1",
  "Main Building B2",
  "Main Building B3",
  "Main Building C1",
  "Main Building C2",
  "Main Building C3",
  "Research Building No. 4",
  "Research Building No. 5",
  "Research Building No. 6",
  "Basic Discipline Building",
  "Research Institute Building",
  "Innovation Center",
  "International Innovation Center",
  "Research Building A/B/C",
  "Building of School of Management and Economics (SME)",
  "New Computer Science Department Building",
  "Comprehensive Gymnasium",
  "Gymnasium",
  "Stadium",
  "Swimming pool",
  "Xuezi Cafeteria",
  "Siyuan Cafeteria",
  "Jiayuan Cafeteria",
  "Yinhua Cafeteria",
  "Zijin Cafeteria",
  "Furong Cafeteria",
  "Xibei Cafeteria",
  "West Gate Bridgehead",
  "Library Bus Stand",
  "Main Building Bus Stand",
  "Gingko Avenue",
  "Multi-use Building",
  "Library",
  "University Hospital",
  "Chengdian Auditorium",
  "Student Activity Center",
  "Time Square",
  "Clock Tower",
  "Lake 1",
  "Lake 2",
  "Commercial Street",
  "National Flag Point",
  "China Construction Bank"
];